name: build

on:
  workflow_dispatch:
    inputs:
      test_build:
        description: 'Test build'
        required: false
        default: 'false'
        type: choice
        options:
        - true
        - false
      fake_build:
        description: 'Fake build'
        required: false
        default: 'false'
        type: choice
        options:
        - true
        - false
      max_speed:
        description: 'Build with max speed'
        required: false
        default: 'true'
        type: choice
        options:
        - true
        - false

  push:
    tags:
      - v[0-9]+*

env:
  TEST_BUILD: ${{ github.event.inputs.test_build == 'true' }}
  FAKE_BUILD: ${{ github.event.inputs.fake_build == 'true' }}
  MAX_SPEED: ${{ github.event.inputs.max_speed != 'false' }}
  TAG_SUFFIX: ${{ github.event.inputs.fake_build == 'true' && '-fake' || github.event.inputs.test_build == 'true' && '-test' || '' }}
  REPO_NAME: zapret-openwrt
  REPO_URL: https://github.com/remittor/zapret-openwrt
  REPO_LNK: remittor/zapret-openwrt
  REPO_BRANCH: master
  PKGDIR: ${{ github.workspace }}/zapret-openwrt
  SDKDIR: /builder
  BUILD_DATE: unknown
  REPO_DATE: unknown
  LUCI_ARCH: aarch64_cortex-a53

jobs:
  check:
    runs-on: ubuntu-24.04
    outputs:
      tag: ${{ steps.gh.outputs.tag }}
      date: ${{ steps.gh.outputs.date }}
      sha: ${{ steps.gh.outputs.sha }}
      url: ${{ steps.gh.outputs.url }}
      message: ${{ steps.gh.outputs.message }}
      build_date: ${{ steps.gh.outputs.build_date }}
      fw_date: ${{ steps.gh.outputs.fw_date }}
      is_active: ${{ steps.activity.outputs.is_active }}
      test_build: ${{ env.TEST_BUILD }}
      fake_build: ${{ env.FAKE_BUILD }}
    steps:
      - name: Get repo data via GH API
        id: gh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH=$(gh api repos/$REPO_LNK --jq '.default_branch')
          REPO_DATE=$(gh api repos/$REPO_LNK/commits/$BRANCH --jq '.commit.committer.date')
          BUILD_DATE=$( date --utc +'%Y%m%d' )
          FW_DATE=$( date --utc +'%Y-%m-%d' )
          {
            echo "tag=$GITHUB_REF_NAME"
            echo "date=$(date --utc -d $REPO_DATE +%Y%m%d)"
            echo "sha=$(gh api repos/$REPO_LNK/commits/$BRANCH --jq '.sha[0:7]')"
            echo "url=$(gh api repos/$REPO_LNK/commits/$BRANCH --jq '.html_url')"
            echo "message<<EOF"
            gh api repos/$REPO_LNK/commits/$BRANCH --jq '.commit.message'
            echo EOF
            echo "build_date=$BUILD_DATE"
            echo "fw_date=$FW_DATE"
          } >> $GITHUB_OUTPUT
          echo "REPO_DATE=$REPO_DATE" >> $GITHUB_ENV

      - name: Check for repo activity
        id: activity
        env:
          REPO_DATE: ${{ env.REPO_DATE }}
          URL: ${{ steps.gh.outputs.url }}
        run: |
          TIMESTAMP=$(date --utc -d $REPO_DATE +%s)
          DAYS=$(( ( $(date --utc +%s) - $TIMESTAMP ) / 86400 ))
          echo "Repository activity: $(date --utc -d $REPO_DATE)"
          echo "Commit: $URL"
          if [ "${{ github.event_name }}" != "schedule" ]; then
            is_active=true
          elif [[ $DAYS -lt 1 ]]; then
            is_active=true
          else
            echo "Repository not updated within last 24 hours."
            is_active=false
          fi
          echo "is_active=$is_active" >> $GITHUB_OUTPUT

  build:
    needs: [ check ]
    name: "${{ matrix.arch }}"
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        arch:
          - aarch64_cortex-a53
          - aarch64_cortex-a72
          - aarch64_cortex-a76
          - aarch64_generic
          - arm_arm1176jzf-s_vfp
          - arm_arm926ej-s
          - arm_cortex-a15_neon-vfpv4
          - arm_cortex-a5_vfpv4
          - arm_cortex-a7
          - arm_cortex-a7_neon-vfpv4
          - arm_cortex-a7_vfpv4
          - arm_cortex-a8_vfpv3
          - arm_cortex-a9
          - arm_cortex-a9_neon
          - mips64_octeonplus
          - mips_24kc
          - mips_mips32
          - mipsel_24kc
          - mipsel_24kc_24kf
          - mipsel_74kc
          - mipsel_mips32
          - riscv64_generic
          - x86_64
        isTestOrFake:
          - ${{ needs.check.outputs.test_build == 'true' || needs.check.outputs.fake_build == 'true' }}
        exclude:
          - { isTestOrFake: true }
        include:
          - arch: aarch64_cortex-a53
          - arch: x86_64
    container:
      image: ghcr.io/openwrt/sdk:${{ matrix.arch }}-v25.12.5
      options: --user root

    outputs:
      pkgver: ${{ steps.prepare.outputs.pkgver }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ env.REPO_LNK }}
          path: ${{ env.REPO_NAME }}

      - name: Fix SDK paths
        run: |
          mkdir -p $SDKDIR/shared-workdir
          rm -rf $SDKDIR/shared-workdir/build
          ln -sf $SDKDIR $SDKDIR/shared-workdir/build

      - name: Initialization environment
        working-directory: ${{ env.SDKDIR }}
        env:
          DEBIAN_FRONTEND: noninteractive
          ARCH_TAG: ${{ matrix.arch }}
        run: |
          echo "PKGTYPE=apk" >> $GITHUB_ENV
          mkdir -p ./logs
          echo "FAKE_BUILD=${{ env.FAKE_BUILD }}" >> $GITHUB_ENV
          echo "ARCH_TAG=$ARCH_TAG" >> $GITHUB_ENV
          echo "TZ=UTC" >> $GITHUB_ENV

      - name: Prepare packages
        id: prepare
        working-directory: ${{ env.SDKDIR }}
        run: |
          MKFN=$( ls -1 $PKGDIR/luci-app-zapret*/Makefile )
          PKGVER=$( grep -s '^PKG_VERSION:=.*' $MKFN | cut -d'=' -f2 )
          PKGREL=$( grep -s '^PKG_RELEASE:=.*' $MKFN | cut -d'=' -f2 )
          [ "$PKGREL" != "1" ] && PKGVER=$PKGVER-r$PKGREL
          echo "PKG_VERSION = $PKGVER"
          cp -vr $PKGDIR ./package/$REPO_NAME/
          echo "PKGVER=$PKGVER" >> $GITHUB_ENV
          echo "pkgver=$PKGVER" >> $GITHUB_OUTPUT
          echo "status=success" >> $GITHUB_OUTPUT

      - name: Init packages
        id: init
        if: steps.prepare.outputs.status == 'success'
        working-directory: ${{ env.SDKDIR }}
        run: |
          mv feeds.conf.default feeds.conf
          sed -i -e 's|base.*\.git|base https://github.com/openwrt/openwrt.git|' feeds.conf
          sed -i -e 's|packages.*\.git|packages https://github.com/openwrt/packages.git|' feeds.conf
          sed -i -e 's|luci.*\.git|luci https://github.com/openwrt/luci.git|' feeds.conf
          ./scripts/feeds update base packages luci
          ./scripts/feeds install -a
          echo "status=success" >> $GITHUB_OUTPUT

      - name: Init config
        id: config
        if: steps.init.outputs.status == 'success'
        working-directory: ${{ env.SDKDIR }}
        run: |
          make defconfig
          sed -i 's/CONFIG_LUCI_JSMIN=y/CONFIG_LUCI_JSMIN=n/g' .config
          sed -i 's/CONFIG_LUCI_CSSTIDY=y/CONFIG_LUCI_CSSTIDY=n/g' .config
          grep -q '^CONFIG_LUCI_CSSTIDY=' .config || echo 'CONFIG_LUCI_CSSTIDY=n' >> .config
          echo "status=success" >> $GITHUB_OUTPUT

      - name: Show config
        working-directory: ${{ env.SDKDIR }}
        run: |
          cat .config || echo "File .config not found"

      - name: Build packages
        id: build
        if: steps.config.outputs.status == 'success' && env.FAKE_BUILD != 'true'
        working-directory: ${{ env.SDKDIR }}
        env:
          ARCH_TAG: ${{ matrix.arch }}
        run: |
          PKGLIST="package/zapret-openwrt/zapret/compile"
          if [ "$ARCH_TAG" = "$LUCI_ARCH" ]; then
            PKGLIST="$PKGLIST package/zapret-openwrt/luci-app-zapret/compile"
          fi
          MAKE_JOBS=$(nproc)
          echo "$MAKE_JOBS thread compile"
          if [ "$MAX_SPEED" != "true" ]; then
            make $PKGLIST V=sc BUILD_LOG=1
          else
            make $PKGLIST -j$MAKE_JOBS
          fi
          echo "status=success" >> $GITHUB_OUTPUT

      - name: Build packages (FAKE)
        id: build_fake
        if: env.FAKE_BUILD == 'true'
        working-directory: ${{ env.SDKDIR }}
        env:
          ARCH_TAG: ${{ matrix.arch }}
        run: |
          OUT_DIR=./bin/packages/dev_x/base
          mkdir -p $OUT_DIR
          touch $OUT_DIR/zapret_$PKGVER-$ARCH_TAG.apk
          touch $OUT_DIR/luci-app-zapret_$PKGVER-all.apk
          echo "status=success" >> $GITHUB_OUTPUT

      - name: Install packages
        id: install
        if: steps.build.outputs.status == 'success' || steps.build_fake.outputs.status == 'success'
        working-directory: ${{ env.SDKDIR }}
        run: |
          find ./bin/packages/*/base -type f ! -regex ".*\(zapret\).*\.apk$" -delete
          OUTDIR=$GITHUB_WORKSPACE/apk-${{ matrix.arch }}
          mkdir -p $OUTDIR
          cp -R ./bin/packages/*/base/. $OUTDIR/
          echo "OUTDIR=$OUTDIR" >> $GITHUB_ENV
          echo "status=success" >> $GITHUB_OUTPUT

      - name: Compress build logs
        if: always()
        env:
          ARCH_TAG: ${{ matrix.arch }}
          LOGS_DIR: ${{ env.SDKDIR }}/logs
        run: |
          tar -cJvf logs-v25.12.5-$ARCH_TAG.tar.xz $LOGS_DIR

      - name: Upload packages
        if: steps.install.outcome == 'success'
        uses: actions/upload-artifact@main
        with:
          path: ${{ env.OUTDIR }}
          name: zapret,apk,${{ matrix.arch }}
          if-no-files-found: error

      - name: Upload build logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          path: logs-*.tar.xz
          name: logs-v25.12.5-${{ matrix.arch }}

  release:
    needs: [ check, build ]
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: zapret,*

      - name: Put packages into zip
        env:
          TAG: ${{ needs.check.outputs.tag }}
          BUILD_DATE: ${{ needs.check.outputs.build_date }}
          PKGVER: ${{ needs.build.outputs.pkgver }}
        run: |
          mkdir -p sorted
          find . -maxdepth 1 -type d -name "zapret,apk,*" -exec sh -c 'mkdir -p sorted/$(basename "{}" | cut -d, -f3)/apk' \;
          find . -maxdepth 1 -type d -name "zapret,apk,*" -exec sh -c 'cp -R "{}/." sorted/$(basename "{}" | cut -d, -f3)/apk' \;
          LUCI_APK=$( find . -type f -path "*/zapret,apk,*/luci-app-zapret*.apk" -print | head -n 1 )
          find ./sorted -mindepth 2 -maxdepth 2 -type d -name "apk" -exec cp -f "$LUCI_APK" "{}/" \;
          mkdir -p public
          find ./sorted -mindepth 1 -maxdepth 1 -type d -exec sh -c '7z a ./public/zapret_v${PKGVER}_$(basename "{}").zip {}/*' \;
          ls -lh ./public/*.zip

      - name: Upload assets
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: ${{ env.TEST_BUILD == 'true' || env.FAKE_BUILD == 'true' }}
          prerelease: true
          tag_name: v${{ needs.build.outputs.pkgver }}${{ env.TAG_SUFFIX }}
          name: zapret v${{ needs.build.outputs.pkgver }}
          body: |
            zapret v${{ needs.build.outputs.pkgver }} for OpenWrt
          files: ./public/*.zip
